version: '3'
services:
  db:
    container_name: mongo-container
    image: mongo:4.4.11
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - api-net
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    networks:
      - api-net
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    depends_on:
      - db
networks:
  api-net: